armadillo:
  oidc-permission-enabled: false
  docker-management-enabled: true
  oidc-admin-user: m.a.swertz@umcg.nl
spring:
  security:
    user:
      name: admin
      password: blaat
    oauth2:
      client:
        registration:
          molgenis:
            client-id: b396233b-cdb2-449e-ac5c-a0d28b38f791
            client-secret: nRO_t1_cIpdzRzr-cWBeZg4ckBsMHmX2MlA9SaSg4P8
        provider:
          molgenis:
            issuer-uri: https://auth.molgenis.org
      resourceserver:
        jwt:
          issuer-uri: https://auth.molgenis.org
        opaquetoken:
          client-id: b396233b-cdb2-449e-ac5c-a0d28b38f791
  config:
    activate:
      on-profile: default