# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      - image: eclipse-temurin:17.0.9_9-jdk-jammy

    working_directory: ~/repo
    resource_class: large

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

    steps:
      - checkout

      - run:
          name: update package manager
          command: apt-get update

      - run:
          name: add packages for docker cli install
          command: apt-get -y install gnupg lsb-release curl

      - run:
          name: update packages again
          command: apt-get update

      - run:
          name: set repo keys for docker packages
          command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

      - run:
          name: add repo for docker packages
          command: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

      - run:
          name: update package manager again
          command: apt-get update

      - run:
          name: Install Docker client
          command: apt-get -y install docker-ce docker-ce-cli containerd.io

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run:
          name: Sign in to docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Setup git
          command: |
            git config --global --add safe.directory '*'
            git config user.email "molgenis@gmail.com"
            git config user.name "molgenis-jenkins"
            git config url.https://.insteadOf git://

      - run:
          name: build, test, push docker
          command: |
            ./gradlew test jacocoMergedReport sonar \
            -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization=molgenis -Dsonar.host.url=https://sonarcloud.io

      - store_artifacts:
          path: build/libs

  build-dev:
    docker:
      # official https://hub.docker.com/r/cimg/openjdk
      - image: cimg/openjdk:17.0

    working_directory: ~/repo
    resource_class: large

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: build, docker
          command: |
            ./gradlew docker
            ./docker/bin/prepare.bash dev

      - run:
          name: Start all services declared in docker-compose.yml
          command: |
            cd ./docker/dev/
            docker-compose up -d

      - run:
          name: Start docker-compose and verify service(s)
          command: |
            cd ./docker/dev/
            docker-compose up -d
            docker container run --network container:dev-armadillo-1 \
              docker.io/jwilder/dockerize \
              -wait http://localhost:8080/ \
              -wait-retry-interval 2s \
              -timeout 20s

  build-ci:
    docker:
      # official https://hub.docker.com/r/cimg/openjdk
      - image: cimg/openjdk:17.0

    working_directory: ~/repo
    resource_class: large

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Armadillo and R CICD image
          command: |
            ./gradlew docker
            ./docker/bin/prepare.bash ci

      - run:
          name: Make sure all images declared in docker-compose.yml are available and ready
          command: |
            cd ./docker/ci/

            docker images ls

            docker-compose build
            docker-compose up -d

            docker images ls

      - run:
          name: Start docker-compose and wait for `release-test.R` to finish
          command: |
            cd ./docker/ci/
            docker-compose up -d

            docker ps

            # Poll on the wrong port to see we get 200 seconds
            docker container run --network container:ci-armadillo-1 \
              docker.io/jwilder/dockerize \
              -wait http://localhost:8080/ \
              -wait-retry-interval 20s \
              -timeout 30s || echo "Timed out"

            docker ps
            docker network ls
            docker network inspect ci_default

            docker container run --network container:ci-armadillo-1 \
              --volume ./fake-tree/cicd:/cicd:rw \
              --interactive --tty \
              --entrypoint /bin/bash molgenis/r-cicd -c "ls -l /cicd ; cd /cicd/scripts/release ; ./armadillo-ready.bash"

            echo "Results"
            cat ./fake-tree/cicd/log/out.log
            cat ./fake-tree/cicd/log/err.log

      - store_artifacts:
          path: ~/repo/docker/ci


workflows:
  version: 2
  build-deploy:
    jobs:
      #- build
      - build-ci
      #- build-dev
