armadillo:
  # set this false if you DON'T want Armadillo to create/edit/delete profile docker images via the user interface
  docker-management-enabled: true

  # uncomment this to configure a default admin user
  # oidc-admin-user: @ADMIN_EMAIL@

  profiles:
    - name: default
      image: datashield/armadillo-rserver
      port: 6311
      package-whitelist:
        - dsBase
      function-blacklist: [ ]
      options:
        datashield:
          # the seed can only be 9 digits
          seed: @SEED@

audit:
  log:
    path: @LOGPATH@/audit.log

spring:
  # optional settings (review spring handbook to find more):
  servlet:
    multipart:
      ## change this if your files are bigger
      max-file-size: 1000MB
      max-request-size: 1000MB
  security:
    user:
      name: @ADMINUSER@
      password: @ADMINPASS@
      roles:
        - SU
    
    oauth2:
      client:
        provider:
          molgenis:
            issuer-uri: @ISSUERURL@
        registration:
          molgenis:
            redirect-uri: 'https://@ARMADILLODOMAIN@/login/oauth2/code/molgenis'
            client-id: @CLIENTID@
            client-secret: @CLIENTSECRET@
      resourceserver:
        jwt:
          issuer-uri: @ISSUERURL@
        opaquetoken:
          client-id: @CLIENTID@

storage:
  root-dir: @DATADIR@
