armadillo:
  oidc-permission-enabled: true
  docker-management-enabled: true
  oidc-admin-user: m.k.slofstra@umcg.nl
spring:
  mvc:
    async:
      request-timeout: 36000000
  servlet:
    multipart:
      max-file-size: 13000MB
      max-request-size: 13000MB
  security:
    user:
      password: admin
    oauth2:
      client:
        provider:
          molgenis:
            issuer-uri: 'https://auth.molgenis.org'
        registration:
          molgenis:
            client-id: b396233b-cdb2-449e-ac5c-a0d28b38f791
            client-secret: nRO_t1_cIpdzRzr-cWBeZg4ckBsMHmX2MlA9SaSg4P8
      resourceserver:
        jwt:
          issuer-uri: 'https://auth.molgenis.org'
        opaquetoken:
          client-id: 'b396233b-cdb2-449e-ac5c-a0d28b38f791'
storage:
  root-dir: /Users/mkslofstra/git/molgenis-service-armadillo/data

logging:
  level:
    ## change to DEBUG to have more details, typically when developing
    org.molgenis: DEBUG
