armadillo:
  # set this to 'true' if you want to accept permissions from oidc provider
  oidc-permission-enabled: false
  # set this true if you want Armadillo to create/edit/delete profile docker images
  docker-management-enabled: true
  # uncomment this to configure a default admin user
  # oidc-admin-user: user@yourdomain.org

  profiles:
    - name: default
      image: datashield/armadillo-rserver
      port: 6311
      package-whitelist:
        - dsBase
      function-blacklist: [ ]
      options:
        datashield:
          # the seed can only be 9 digits
          seed: 342325352
          # foo: bar

springdoc:
  swagger-ui:
    enabled: true
    operationsSorter: alpha
    csrf:
      enabled: true

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: armadillo
  security:
    user:
      name: admin
      roles:
        - SU

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  forward-headers-strategy: framework
  error:
    include-binding-errors: always
    include-message: always

audit:
  log:
    path: logs/audit.log

logging:
  config: classpath:logback-file.xml

storage:
  root-dir: data

---
# 'basic' profile is a configuration without oidc
# you can only sign in using basicauth 'admin' 'admin'

spring:
  security:
    user:
      password: admin
  config:
    activate:
      on-profile: basic

storage:
  root-dir: data

---
spring:
  security:
    user:
      password: admin
    oauth2:
      client:
        # Uncomment the following section to enable OIDC login:
        #        registration:
        #            molgenis:
        #               client-id: <your client id>
        #               client-secret: <your client secret>
        provider:
          molgenis:
            issuer-uri: 'https://auth.molgenis.org'
      resourceserver:
        jwt:
          issuer-uri: 'https://auth.molgenis.org'
        opaquetoken:
          client-id: 'b396233b-cdb2-449e-ac5c-a0d28b38f791'
  config:
    activate:
      on-profile: development

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread|%.8X{sessionID}] %-5level %logger{36} - %msg%n"
  level:
    org.molgenis: DEBUG
    org:
      springframework:
        security: DEBUG
        boot:
          actuate:
            audit:
              listener:
                AuditListener: INFO
          web:
            context: DEBUG

storage:
  root-dir: data

# Uncomment the following block to enable MinIO storage (overrules local storage)
#minio:
#  url: http://localhost
#  port: 9000
#  access-key: molgenis
#  secret-key: molgenis

---
spring:
  config:
    activate:
      on-profile: development-omics

armadillo:
  profiles:
    - name: default
      port: 6311
      whitelist:
        - dsBase
      options:
        datashield:
          seed: 342325352
    - name: omics
      port: 6313
      whitelist:
        - dsBase
        - dsOmics
        - resourcer
        - s3.file.resourcer
      options:
        datashield:
          seed: 712368126

---
spring:
  config:
    activate:
      on-profile: development-exposome

armadillo:
  profiles:
    - name: default
      environment: default
      port: 6311
      whitelist:
        - dsBase
      options:
        datashield:
          seed: 342325352
    - name: exposome
      environment: exposome
      port: 6312
      whitelist:
        - dsBase
        - dsExposome
      options:
        datashield:
          seed: 039284230

---
# use this profile when you want to run the armadillo within the docker-compose file
spring:
  config:
    activate:
      on-profile: docker-compose

armadillo:
  profiles:
    - name: default
      host: rserver
      port: 6311
      whitelist:
        - dsBase
      options:
        datashield:
          seed: 342325352
    - name: exposome
      environment: exposome
      host: rserver-exposome
      port: 6311
      whitelist:
        - dsBase
        - dsExposome
      options:
        datashield:
          seed: 039284230
    - name: omics
      environment: omics
      host: rserver-omics
      port: 6311
      whitelist:
        - dsBase
        - dsOmics
        - resourcer
        - s3.file.resourcer
      options:
        datashield:
          seed: 93787423
