version: "3.4"
services:
  armadillo:
    hostname: armadillo
    ports:
      - 8080:8080

    build:
      context: '.'
      dockerfile: 'Dockerfile'
      args:
        JAR_FILE: '*.jar'

    image: molgenis/molgenis-armadillo-snapshot:latest
    environment:
      LOGGING_CONFIG: 'classpath:logback-file.xml'
      AUDIT_LOG_PATH: '/app/logs/audit.log'
      SPRING_SECURITY_USER_PASSWORD: 'admin'
    volumes:
      - ${PWD}/armadillo/logs:/logs
      - ${PWD}/armadillo/data:/data
      - ${PWD}/armadillo/config:/config
      - /var/run/docker.sock:/var/run/docker.sock

  default:
    hostname: default
    image: datashield/rock-base:latest
    environment:
      DEBUG: "TRUE"

  xenon:
    hostname: xenon
    image: datashield/rock-dolomite-xenon:latest
    environment:
      DEBUG: "TRUE"

  rock:
    hostname: rock
    image: datashield/rock-base:latest
    environment:
      DEBUG: "TRUE"
